name: Ejecutar Script Python Automáticamente

on:
  schedule:
    - cron: "0 7-23 * * *"  # Se ejecuta cada hora de 7 AM a 11 PM (UTC)
  workflow_dispatch:  # Permite ejecutar manualmente desde GitHub

jobs:
  run_script:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar el repositorio
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11.9"

      - name: Instalar dependencias
        run: pip install --upgrade pip && pip install -r requirements.txt

      - name: Ejecutar el script
        env:
          EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}  # Se pasa el secreto como variable de entorno
        run: python main.py
