name: Ejecutar Script Python Automáticamente

on:
  schedule:
    - cron: "0 0,6,12,18 * * *"  # Se ejecuta a las 00:00, 06:00, 12:00 y 18:00 UTC

  workflow_dispatch:  # Permite ejecutar manualmente desde GitHub

jobs:
  run_script:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar el repositorio
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11.9"

      - name: Instalar dependencias
        run: pip install --upgrade pip && pip install -r requirements.txt

      - name: Ejecutar el script
        run: python main.py
